version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '${APP_PORT:-8000}:80'
    environment:
      PHP_USER_ID: '${PHP_USER_ID}'
    networks:
      - network
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql_volume:/var/lib/mysql'
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT:-8080}:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    networks:
      - network
    depends_on:
      - mysql
networks:
  network:
    driver: bridge
volumes:
  mysql_volume:
    driver: local
